[versions]
kotlin = "2.1.0"
kermit = "2.0.5"
better-parse = "0.4.4"

# Plugins
agp = "8.2.2"

#Android
minSdk = "21"
compileSdk = "35"
targetSdk = "35"

[libraries]
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
betterParse = { module = "com.github.h0tk3y.betterParse:better-parse", version.ref = "better-parse" }
koltin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }