package com.shepeliev.ksdp.grammar

import com.github.h0tk3y.betterParse.grammar.Grammar

abstract class BaseGrammar<out T> : Grammar<T>() {
    protected val x00 by _x00 // NUL
    protected val x01 by _x01 // SOH
    protected val x02 by _x02 // STX
    protected val x03 by _x03 // ETX
    protected val x04 by _x04 // EOT
    protected val x05 by _x05 // ENQ
    protected val x06 by _x06 // ACK
    protected val x07 by _x07 // BEL
    protected val x08 by _x08 // BS
    protected val x09 by _x09 // HT
    protected val x0A by _x0A // LF
    protected val x0B by _x0B // VT
    protected val x0C by _x0C // FF
    protected val x0D by _x0D // CR
    protected val x0E by _x0E // SO
    protected val x0F by _x0F // SI
    protected val x10 by _x10 // DLE
    protected val x11 by _x11 // DC1
    protected val x12 by _x12 // DC2
    protected val x13 by _x13 // DC3
    protected val x14 by _x14 // DC4
    protected val x15 by _x15 // NAK
    protected val x16 by _x16 // SYN
    protected val x17 by _x17 // ETB
    protected val x18 by _x18 // CAN
    protected val x19 by _x19 // EM
    protected val x1A by _x1A // SUB
    protected val x1B by _x1B // ESC
    protected val x1C by _x1C // FS
    protected val x1D by _x1D // GS
    protected val x1E by _x1E // RS
    protected val x1F by _x1F // US
    protected val x20 by _x20 // SP
    protected val x21 by _x21 // !
    protected val x22 by _x22 // "
    protected val x23 by _x23 // #
    protected val x24 by _x24 // $
    protected val x25 by _x25 // %
    protected val x26 by _x26 // &
    protected val x27 by _x27 // '
    protected val x28 by _x28 // (
    protected val x29 by _x29 // )
    protected val x2A by _x2A // *
    protected val x2B by _x2B // +
    protected val x2C by _x2C // ,
    protected val x2D by _x2D // -
    protected val x2E by _x2E // .
    protected val x2F by _x2F // /
    protected val x30 by _x30 // 0
    protected val x31 by _x31 // 1
    protected val x32 by _x32 // 2
    protected val x33 by _x33 // 3
    protected val x34 by _x34 // 4
    protected val x35 by _x35 // 5
    protected val x36 by _x36 // 6
    protected val x37 by _x37 // 7
    protected val x38 by _x38 // 8
    protected val x39 by _x39 // 9
    protected val x3A by _x3A // :
    protected val x3B by _x3B // ;
    protected val x3C by _x3C // <
    protected val x3D by _x3D // =
    protected val x3E by _x3E // >
    protected val x3F by _x3F // ?
    protected val x40 by _x40 // @
    protected val x41 by _x41 // A
    protected val x42 by _x42 // B
    protected val x43 by _x43 // C
    protected val x44 by _x44 // D
    protected val x45 by _x45 // E
    protected val x46 by _x46 // F
    protected val x47 by _x47 // G
    protected val x48 by _x48 // H
    protected val x49 by _x49 // I
    protected val x4A by _x4A // J
    protected val x4B by _x4B // K
    protected val x4C by _x4C // L
    protected val x4D by _x4D // M
    protected val x4E by _x4E // N
    protected val x4F by _x4F // O
    protected val x50 by _x50 // P
    protected val x51 by _x51 // Q
    protected val x52 by _x52 // R
    protected val x53 by _x53 // S
    protected val x54 by _x54 // T
    protected val x55 by _x55 // U
    protected val x56 by _x56 // V
    protected val x57 by _x57 // W
    protected val x58 by _x58 // X
    protected val x59 by _x59 // Y
    protected val x5A by _x5A // Z
    protected val x5B by _x5B // [
    protected val x5C by _x5C // \
    protected val x5D by _x5D // ]
    protected val x5E by _x5E // ^
    protected val x5F by _x5F // _
    protected val x60 by _x60 // `
    protected val x61 by _x61 // a
    protected val x62 by _x62 // b
    protected val x63 by _x63 // c
    protected val x64 by _x64 // d
    protected val x65 by _x65 // e
    protected val x66 by _x66 // f
    protected val x67 by _x67 // g
    protected val x68 by _x68 // h
    protected val x69 by _x69 // i
    protected val x6A by _x6A // j
    protected val x6B by _x6B // k
    protected val x6C by _x6C // l
    protected val x6D by _x6D // m
    protected val x6E by _x6E // n
    protected val x6F by _x6F // o
    protected val x70 by _x70 // p
    protected val x71 by _x71 // q
    protected val x72 by _x72 // r
    protected val x73 by _x73 // s
    protected val x74 by _x74 // t
    protected val x75 by _x75 // u
    protected val x76 by _x76 // v
    protected val x77 by _x77 // w
    protected val x78 by _x78 // x
    protected val x79 by _x79 // y
    protected val x7A by _x7A // z
    protected val x7B by _x7B // {
    protected val x7C by _x7C // |
    protected val x7D by _x7D // }
    protected val x7E by _x7E // ~
    protected val x7F by _x7F // DEL
    protected val x80 by _x80 // <control-80>
    protected val x81 by _x81 // <control-81>
    protected val x82 by _x82 // <control-82>
    protected val x83 by _x83 // <control-83>
    protected val x84 by _x84 // <control-84>
    protected val x85 by _x85 // <control-85>
    protected val x86 by _x86 // <control-86>
    protected val x87 by _x87 // <control-87>
    protected val x88 by _x88 // <control-88>
    protected val x89 by _x89 // <control-89>
    protected val x8A by _x8A // <control-8A>
    protected val x8B by _x8B // <control-8B>
    protected val x8C by _x8C // <control-8C>
    protected val x8D by _x8D // <control-8D>
    protected val x8E by _x8E // <control-8E>
    protected val x8F by _x8F // <control-8F>
    protected val x90 by _x90 // <control-90>
    protected val x91 by _x91 // <control-91>
    protected val x92 by _x92 // <control-92>
    protected val x93 by _x93 // <control-93>
    protected val x94 by _x94 // <control-94>
    protected val x95 by _x95 // <control-95>
    protected val x96 by _x96 // <control-96>
    protected val x97 by _x97 // <control-97>
    protected val x98 by _x98 // <control-98>
    protected val x99 by _x99 // <control-99>
    protected val x9A by _x9A // <control-9A>
    protected val x9B by _x9B // <control-9B>
    protected val x9C by _x9C // <control-9C>
    protected val x9D by _x9D // <control-9D>
    protected val x9E by _x9E // <control-9E>
    protected val x9F by _x9F // <control-9F>
    protected val xA0 by _xA0 // <control-A0>
    protected val xA1 by _xA1 // <control-A1>
    protected val xA2 by _xA2 // <control-A2>
    protected val xA3 by _xA3 // <control-A3>
    protected val xA4 by _xA4 // <control-A4>
    protected val xA5 by _xA5 // <control-A5>
    protected val xA6 by _xA6 // <control-A6>
    protected val xA7 by _xA7 // <control-A7>
    protected val xA8 by _xA8 // <control-A8>
    protected val xA9 by _xA9 // <control-A9>
    protected val xAA by _xAA // <control-AA>
    protected val xAB by _xAB // <control-AB>
    protected val xAC by _xAC // <control-AC>
    protected val xAD by _xAD // <control-AD>
    protected val xAE by _xAE // <control-AE>
    protected val xAF by _xAF // <control-AF>
    protected val xB0 by _xB0 // <control-B0>
    protected val xB1 by _xB1 // <control-B1>
    protected val xB2 by _xB2 // <control-B2>
    protected val xB3 by _xB3 // <control-B3>
    protected val xB4 by _xB4 // <control-B4>
    protected val xB5 by _xB5 // <control-B5>
    protected val xB6 by _xB6 // <control-B6>
    protected val xB7 by _xB7 // <control-B7>
    protected val xB8 by _xB8 // <control-B8>
    protected val xB9 by _xB9 // <control-B9>
    protected val xBA by _xBA // <control-BA>
    protected val xBB by _xBB // <control-BB>
    protected val xBC by _xBC // <control-BC>
    protected val xBD by _xBD // <control-BD>
    protected val xBE by _xBE // <control-BE>
    protected val xBF by _xBF // <control-BF>
    protected val xC0 by _xC0 // <control-C0>
    protected val xC1 by _xC1 // <control-C1>
    protected val xC2 by _xC2 // <control-C2>
    protected val xC3 by _xC3 // <control-C3>
    protected val xC4 by _xC4 // <control-C4>
    protected val xC5 by _xC5 // <control-C5>
    protected val xC6 by _xC6 // <control-C6>
    protected val xC7 by _xC7 // <control-C7>
    protected val xC8 by _xC8 // <control-C8>
    protected val xC9 by _xC9 // <control-C9>
    protected val xCA by _xCA // <control-CA>
    protected val xCB by _xCB // <control-CB>
    protected val xCC by _xCC // <control-CC>
    protected val xCD by _xCD // <control-CD>
    protected val xCE by _xCE // <control-CE>
    protected val xCF by _xCF // <control-CF>
    protected val xD0 by _xD0 // <control-D0>
    protected val xD1 by _xD1 // <control-D1>
    protected val xD2 by _xD2 // <control-D2>
    protected val xD3 by _xD3 // <control-D3>
    protected val xD4 by _xD4 // <control-D4>
    protected val xD5 by _xD5 // <control-D5>
    protected val xD6 by _xD6 // <control-D6>
    protected val xD7 by _xD7 // <control-D7>
    protected val xD8 by _xD8 // <control-D8>
    protected val xD9 by _xD9 // <control-D9>
    protected val xDA by _xDA // <control-DA>
    protected val xDB by _xDB // <control-DB>
    protected val xDC by _xDC // <control-DC>
    protected val xDD by _xDD // <control-DD>
    protected val xDE by _xDE // <control-DE>
    protected val xDF by _xDF // <control-DF>
    protected val xE0 by _xE0 // <control-E0>
    protected val xE1 by _xE1 // <control-E1>
    protected val xE2 by _xE2 // <control-E2>
    protected val xE3 by _xE3 // <control-E3>
    protected val xE4 by _xE4 // <control-E4>
    protected val xE5 by _xE5 // <control-E5>
    protected val xE6 by _xE6 // <control-E6>
    protected val xE7 by _xE7 // <control-E7>
    protected val xE8 by _xE8 // <control-E8>
    protected val xE9 by _xE9 // <control-E9>
    protected val xEA by _xEA // <control-EA>
    protected val xEB by _xEB // <control-EB>
    protected val xEC by _xEC // <control-EC>
    protected val xED by _xED // <control-ED>
    protected val xEE by _xEE // <control-EE>
    protected val xEF by _xEF // <control-EF>
    protected val xF0 by _xF0 // <control-F0>
    protected val xF1 by _xF1 // <control-F1>
    protected val xF2 by _xF2 // <control-F2>
    protected val xF3 by _xF3 // <control-F3>
    protected val xF4 by _xF4 // <control-F4>
    protected val xF5 by _xF5 // <control-F5>
    protected val xF6 by _xF6 // <control-F6>
    protected val xF7 by _xF7 // <control-F7>
    protected val xF8 by _xF8 // <control-F8>
    protected val xF9 by _xF9 // <control-F9>
    protected val xFA by _xFA // <control-FA>
    protected val xFB by _xFB // <control-FB>
    protected val xFC by _xFC // <control-FC>
    protected val xFD by _xFD // <control-FD>
    protected val xFE by _xFE // <control-FE>
    protected val xFF by _xFF // <control-FF>
}